export const REGIONS = [
  { id: 'SEOUL', label: '서울' },
  { id: 'BUSAN', label: '부산' },
  { id: 'DAEGU', label: '대구' },
  { id: 'INCHEON', label: '인천' },
  { id: 'GWANGJU', label: '광주' },
  { id: 'DAEJEON', label: '대전' },
  { id: 'ULSAN', label: '울산' },
  { id: 'SEJONG', label: '세종' },
  { id: 'GYEONGGI_NORTH', label: '경기 북부' },
  { id: 'GYEONGGI_SOUTH', label: '경기 남부' },
  { id: 'GANGWON', label: '강원' },
  { id: 'CHUNGBUK', label: '충북' },
  { id: 'CHUNGNAM', label: '충남' },
  { id: 'JEONBUK', label: '전북' },
  { id: 'JEONNAM', label: '전남' },
  { id: 'GYEONGBUK', label: '경북' },
  { id: 'GYEONGNAM', label: '경남' },
  { id: 'JEJU', label: '제주' },
] as const;
