import { nanumSquare } from '@repo/fonts';
import { QueryProvider } from '@repo/providers';
import { themeClass } from '@repo/styles/tokens';
import '@repo/styles/reset';
import '@repo/styles/globals';
import clsx from 'clsx';
import { Suspense } from 'react';

import type { Metadata } from 'next';

import { Container } from '@/components/layout/Container';
import { Footer } from '@/components/layout/Footer';
import { Header } from '@/components/layout/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={clsx(nanumSquare.variable, themeClass)}>
      <body>
        <Suspense fallback={null}>
          <Header />
        </Suspense>
        <QueryProvider>
          <Container>{children}</Container>
        </QueryProvider>
        <Footer />
      </body>
    </html>
  );
}
